apiVersion: v1
kind: Service
metadata:
  name: online-library-service
  namespace: online-library
spec:
  selector:
    app: online-library
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
      nodePort: 30080
  type: NodePort
