apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-library-ingress
  namespace: online-library
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: library.local
      http:
        paths:
          - path: /online-library
            pathType: Prefix
            backend:
              service:
                name: online-library-service
                port:
                  number: 8080
    - host: prometheus.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
