apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: online-library
type: Opaque
data:
  root-password: WU9VUl9CQVNFNJRFX0VOQ09ERURfUEFTU1dPUkRfSEVSRQ==  # ← Remplacer par votre mot de passe encodé
  database: b25saW5lX2xpYnJhcnk=  # "online_library" en base64

